# Generated by Django 5.0.2 on 2024-02-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='user_email',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
